model: BaselineModel

data:
  sample_rate: 44100
  batch_size: 8
  n_workers: 16
  mono: true
  base_data_path: './data/dcase'
  normalize_audio: false
  multi_stream: false

experiment:
  learning_rate: 0.001
  max_epochs: 200
  n_label: 15
  optimizer_type: "adam"
  use_scheduler: false

network:
  n_fft: 2048
  hop_length: 882
  n_mels: 40
  n_context: 5
  n_hidden: 50
  n_hidden_layers: 2
  dropout: 0.2
  f_min: 0
  f_max: 22050
#  random_seed: 0

training:
  max_epochs: 200
  strategy: auto
  accelerator: auto
  devices: 1

logging:
  tb_log_dir: "./data/tb_logs/"
  ckpt_dir: "./data/ckpts/"
