model: CNNModel

data:
  sample_rate: 44100
  batch_size: 128
  n_workers: 8
  mono: true
  multi_stream: false
  base_data_path: './data/dcase'

experiment:
  learning_rate: 0.02
  max_epochs: 200
  n_label: 15
  optimizer_type: "SGD"
  use_scheduler: true

network:
  n_fft: 2048
  n_mels: 128
  dropout: 0.0
  f_min: 0
  f_max: 22050
  cnn_conv_channels: [ 32, 64, 128, 256 ]
  last_layer_pooling: true
  pooling: [ 2,2 ]
  classifier_hidden: 512

augmentation:
  cnn_spec_augment: true
  cnn_freq_mask_param: 15
  cnn_time_mask_param: 20
  cnn_n_freq_masks: 2
  cnn_n_time_masks: 2
  cnn_use_mixup: false
  cnn_mixup_alpha: 0.05

training:
  max_epochs: 200
  strategy: auto
  accelerator: auto
  devices: 1

logging:
  tb_log_dir: "./data/tb_logs/"
  ckpt_dir: "./data/ckpts/"