model: EnsembleCNNModel

data:
  base_data_path: "./data/dcase"
  sample_rate: 44100
  mono: false
  multi_stream: true
  stream_cache_dir: "./data/dcase/preprocessed_features"
  resample_cache_dir: "./data/dcase/resampled_audio"
  precompute_mel: true
  mel_cache_dir: "./data/dcase/precomputed_mels"
  mel_config:
    n_fft: 2048
    f_min: 0.0
    f_max: 22050.0
    n_mels: 80
  batch_size: 64
  n_workers: 8

experiment:
  n_label: 15
  max_epochs: 200
  learning_rate: 0.02
  optimizer_type: "SGD"
  use_scheduler: true

network:
  cnn_config:
    n_label: 15
    n_mels: 128
    dropout: 0.0
    last_layer_pooling: true
    pooling: [ 2,2 ]
#    cnn_conv_channels: [ 32, 64, 128, 256 ]
    cnn_conv_channels: [ 32, 64, 128, 256 ]
    classifier_hidden: 512
    cnn_spec_augment: true
    cnn_use_mixup: false
    cnn_freq_mask_param: 15
    cnn_time_mask_param: 20
    cnn_n_freq_masks: 2
    cnn_n_time_masks: 2
    cnn_mixup_alpha: 0.05

  dccnn_config:
    n_label: 15
    n_mels: 128
    dropout: 0.0
    last_layer_pooling: true
    pooling: [ 2,2 ]
#    dccnn_conv_channels: [ 32, 64, 128, 256 ]
    dccnn_conv_channels: [ 32, 64, 128, 256 ]
    classifier_hidden: 512
    dccnn_spec_augment: true
    dccnn_use_mixup: false
    dccnn_freq_mask_param: 15
    dccnn_time_mask_param: 20
    dccnn_n_freq_masks: 2
    dccnn_n_time_masks: 2
    dccnn_mixup_alpha: 0.05

training:
  max_epochs: 200
  strategy: auto
  accelerator: auto
  devices: 1
  precision: 16
  accumulate_grad_batches: 1

logging:
  tb_log_dir: "./data/tb_logs/"
  ckpt_dir: "./data/ckpts/"
