model: CNNModel

data:
  sample_rate: 44100
  batch_size: 64
  n_workers: 8
  mono: false
  normalize_audio: true
  multi_stream: true
  stream_cache_dir: "./data/dcase/preprocessed_features"
  input_stream: "percussive"
  base_data_path: './data/dcase'

experiment:
  learning_rate: 0.02
  max_epochs: 200
  n_label: 15
  optimizer_type: "SGD"
  use_scheduler: true

network:
  n_fft: 2048
  n_mels: 128
  dropout: 0.5
  f_min: 0
  f_max: 22050
  conv_channels: [ 32, 64, 128, 256 ]
  last_layer_pooling: true
  pooling: [ 2,2 ]
  use_classifier: true
  classifier_hidden: 512

augmentation:
  spec_augment: true
  freq_mask_param: 15
  time_mask_param: 20
  n_freq_masks: 2
  n_time_masks: 2
  use_mixup: true
  mixup_alpha: 0.2

training:
  max_epochs: 200
  strategy: auto
  accelerator: auto
  devices: 1
  precision: 32
  accumulate_grad_batches: 2

logging:
  tb_log_dir: "./data/tb_logs/"
  ckpt_dir: "./data/ckpts/cnn_percussive"
