model: EnsembleCNNModel

data:
  base_data_path: "./data/dcase"
  sample_rate: 44100
  mono: false
  multi_stream: true
  batch_size: 16
  n_workers: 4

experiment:
  n_label: 15
  max_epochs: 200
  learning_rate: 0.0001

network:
  cnn_config:
    n_label: 15
    n_mels: 40
    dropout: 0.3
    last_layer_pooling: false
    pooling: [ 2,2 ]
    cnn_conv_channels: [ 64, 128, 256 ]
    classifier_hidden: 128
    cnn_spec_augment: true
    cnn_use_mixup: false
    cnn_freq_mask_param: 4
    cnn_time_mask_param: 6
    cnn_n_freq_masks: 1
    cnn_n_time_masks: 1
    cnn_mixup_alpha: 0.05

  dccnn_config:
    n_label: 15
    n_mels: 40
    dropout: 0.3
    last_layer_pooling: false
    pooling: [ 2,2 ]
    dccnn_conv_channels: [ 64, 128, 256 ]
    classifier_hidden: 128
    dccnn_spec_augment: true
    dccnn_use_mixup: false
    dccnn_freq_mask_param: 4
    dccnn_time_mask_param: 6
    dccnn_n_freq_masks: 1
    dccnn_n_time_masks: 1
    dccnn_mixup_alpha: 0.05

training:
  max_epochs: 200
  strategy: auto
  accelerator: auto
  devices: 1

logging:
  tb_log_dir: "./data/tb_logs/"
  ckpt_dir: "./data/ckpts/"